# Package
[package]
name = "suon"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bevy.workspace = true

# Workspace
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0-dev"
edition = "2024"
repository = "https://github.com/suonengine/suon"

[workspace.dependencies]
bevy = { version = "0.17.2", default-features = false, features = [
  "multi_threaded",
  "sysinfo_plugin",
  "bevy_log",
] }
bytes = "1.10.1"
thiserror = "2.0.17"
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = { version = "2.0.108" }

suon_checksum = { path = "crates/suon_checksum" }
suon_macros = { path = "crates/suon_macros" }
suon_database = { path = "crates/suon_database" }
suon_task = { path = "crates/suon_task" }
suon_xtea = { path = "crates/suon_xtea" }

# Dev profile: use a small amount of optimization to keep compile times fast during development
[profile.dev]
opt-level = 1

# Dev profile for all dependencies: use maximum optimization to improve dependency performance
[profile.dev.package."*"]
opt-level = 3

# Release profile: increase optimization at the cost of longer compile times
[profile.release]
# Compile the entire crate as a single unit for better optimization
# This may slow down compilation slightly but can improve performance
codegen-units = 1
# Enable Thin LTO (Link Time Optimization) for a second optimization pass
# Improves runtime performance across the crate and dependencies
lto = "thin"
