[package]
name = "suon_macros"
version.workspace = true
edition.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
name = "suon_macros"
path = "src/lib.rs"
proc-macro = true
