name: Unused dependencies

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  udeps:
    name: Running udeps
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
      - uses: baptiste0928/cargo-install@v3.3.2
        with:
          crate: cargo-udeps

      - name: Run udeps
        run: rustup run nightly cargo udeps --all --all-features
